(function($){"use strict";function funiter_resizeMegamenu(){var window_size=jQuery('body').innerWidth();window_size+=funiter_get_scrollbar_width();if(window_size>991){$('.funiter-menu-wapper').each(function(){if($(this).length>0){var container=$(this);if(container!='undefined'){var container_width=0,container_offset=container.offset();container_width=container.innerWidth();setTimeout(function(){$('.funiter-menu-wapper .item-megamenu').each(function(index,element){$(element).children('.megamenu').css({'max-width':container_width+'px'});var sub_menu_width=$(element).children('.megamenu').outerWidth(),item_width=$(element).outerWidth(),container_left=container_offset.left,container_right=(container_left+container_width),item_left=$(element).offset().left,overflow_left=(sub_menu_width/2>(item_left-container_left)),overflow_right=((sub_menu_width/2+item_left)>container_right);$(element).children('.megamenu').css({'left':'-'+(sub_menu_width/2-item_width/2)+'px'});if(overflow_left){var left=(item_left-container_left);$(element).children('.megamenu').css({'left':-left+'px'});}
if(overflow_right&&!overflow_left){var left=(item_left-container_left);left=left-(container_width-sub_menu_width);$(element).children('.megamenu').css({'left':-left+'px'});}})},100);}}})}}
function funiter_auto_width_vertical_menu(){var full_width=parseInt($('.container').innerWidth())-30;$('.funiter-menu-wapper.vertical.support-mega-menu').each(function(){var menu_width=parseInt($(this).actual('width')),w=(full_width-menu_width);if(w>0){$(this).find('.megamenu').each(function(){var style=$(this).attr("style");style=(style==undefined)?'':style;style=style+' max-width:'+w+'px;';$(this).attr('style',style);});}})}
function funiter_get_scrollbar_width(){var $inner=jQuery('<div style="width:100%;height:200px;">test</div>'),$outer=jQuery('<div style="width:200px;height:150px;position:absolute;top:0;left:0;visibility:hidden;overflow:hidden;"></div>').append($inner),inner=$inner[0],outer=$outer[0];jQuery('body').append(outer);var width1=inner.offsetWidth;$outer.css('overflow','scroll');var width2=outer.clientWidth;$outer.remove();return(width1-width2);}
function funiter_menuclone_all_menus(){if(!$('.funiter-menu-clone-wrap').length&&$('.funiter-clone-mobile-menu').length>0){$('body').prepend('<div class="funiter-menu-clone-wrap">'+'<div class="funiter-menu-panels-actions-wrap"><a class="funiter-menu-close-btn funiter-menu-close-panels" href="#">x</a></div>'+'<div class="funiter-menu-panels"></div>'+'</div>');}
var i=0,panels_html_args=Array();if(!$('.funiter-menu-clone-wrap .funiter-menu-panels #funiter-menu-panel-main').length){$('.funiter-menu-clone-wrap .funiter-menu-panels').append('<div id="funiter-menu-panel-main" class="funiter-menu-panel funiter-menu-panel-main"><ul class="depth-01"></ul></div>');}
$('.funiter-clone-mobile-menu').each(function(){var $this=$(this),thisMenu=$this,this_menu_id=thisMenu.attr('id'),this_menu_clone_id='funiter-menu-clone-'+this_menu_id;if(!$('#'+this_menu_clone_id).length){var thisClone=$this.clone(true);thisClone.find('.menu-item').addClass('clone-menu-item');thisClone.find('[id]').each(function(){thisClone.find('.vc_tta-panel-heading a[href="#'+$(this).attr('id')+'"]').attr('href','#'+funiter_menuadd_string_prefix($(this).attr('id'),'funiter-menu-clone-'));thisClone.find('.funiter-menu-tabs .tabs-link a[href="#'+$(this).attr('id')+'"]').attr('href','#'+funiter_menuadd_string_prefix($(this).attr('id'),'funiter-menu-clone-'));$(this).attr('id',funiter_menuadd_string_prefix($(this).attr('id'),'funiter-menu-clone-'));});thisClone.find('.funiter-menu-menu').addClass('funiter-menu-menu-clone');var thisMainPanel=$('.funiter-menu-clone-wrap .funiter-menu-panels #funiter-menu-panel-main ul');thisMainPanel.append(thisClone.html());funiter_menu_insert_children_panels_html_by_elem(thisMainPanel,i);}});}
function funiter_menu_insert_children_panels_html_by_elem($elem,i){if($elem.find('.menu-item-has-children').length){$elem.find('.menu-item-has-children').each(function(){var thisChildItem=$(this);funiter_menu_insert_children_panels_html_by_elem(thisChildItem,i);var next_nav_target='funiter-menu-panel-'+i;while($('#'+next_nav_target).length){i++;next_nav_target='funiter-menu-panel-'+i;}
thisChildItem.prepend('<a class="funiter-menu-next-panel" href="#'+next_nav_target+'" data-target="#'+next_nav_target+'"></a>');var sub_menu_html=$('<div>').append(thisChildItem.find('> .submenu').clone()).html();thisChildItem.find('> .submenu').remove();$('.funiter-menu-clone-wrap .funiter-menu-panels').append('<div id="'+next_nav_target+'" class="funiter-menu-panel funiter-menu-sub-panel funiter-menu-hidden">'+sub_menu_html+'</div>');});}}
function funiter_menuadd_string_prefix(str,prefix){return prefix+str;}
function funiter_menuget_url_var(key,url){var result=new RegExp(key+"=([^&]*)","i").exec(url);return result&&result[1]||"";}
$(document).ready(function(){funiter_resizeMegamenu();$(document).on('click','.menu-toggle',function(){$('.funiter-menu-clone-wrap').addClass('open');return false;});$(document).on('click','.funiter-menu-clone-wrap .funiter-menu-close-panels',function(){$('.funiter-menu-clone-wrap').removeClass('open');return false;});$(document).on('click',function(event){if(event.offsetX>$('.funiter-menu-clone-wrap').width())
$('.funiter-menu-clone-wrap').removeClass('open');});$(document).on('click','.funiter-menu-next-panel',function(e){var $this=$(this),thisItem=$this.closest('.menu-item'),thisPanel=$this.closest('.funiter-menu-panel'),target_id=$this.attr('href');if($(target_id).length){thisPanel.addClass('funiter-menu-sub-opened');$(target_id).addClass('funiter-menu-panel-opened').removeClass('funiter-menu-hidden').attr('data-parent-panel',thisPanel.attr('id'));var item_title=thisItem.find('.funiter-menu-item-title').attr('title'),firstItemTitle='';if($('.funiter-menu-panels-actions-wrap .funiter-menu-current-panel-title').length>0){firstItemTitle=$('.funiter-menu-panels-actions-wrap .funiter-menu-current-panel-title').html();}
if(typeof item_title!='undefined'&&typeof item_title!=false){if(!$('.funiter-menu-panels-actions-wrap .funiter-menu-current-panel-title').length){$('.funiter-menu-panels-actions-wrap').prepend('<span class="funiter-menu-current-panel-title"></span>');}
$('.funiter-menu-panels-actions-wrap .funiter-menu-current-panel-title').html(item_title);}
else{$('.funiter-menu-panels-actions-wrap .funiter-menu-current-panel-title').remove();}
$('.funiter-menu-panels-actions-wrap .funiter-menu-prev-panel').remove();$('.funiter-menu-panels-actions-wrap').prepend('<a data-prenttitle="'+firstItemTitle+'" class="funiter-menu-prev-panel" href="#'+thisPanel.attr('id')+'" data-cur-panel="'+target_id+'" data-target="#'+thisPanel.attr('id')+'"></a>');}
e.preventDefault();});$(document).on('click','.funiter-menu-prev-panel',function(e){var $this=$(this),cur_panel_id=$this.attr('data-cur-panel'),target_id=$this.attr('href');$(cur_panel_id).removeClass('funiter-menu-panel-opened').addClass('funiter-menu-hidden');$(target_id).addClass('funiter-menu-panel-opened').removeClass('funiter-menu-sub-opened');var new_parent_panel_id=$(target_id).attr('data-parent-panel');if(typeof new_parent_panel_id=='undefined'||typeof new_parent_panel_id==false){$('.funiter-menu-panels-actions-wrap .funiter-menu-prev-panel').remove();$('.funiter-menu-panels-actions-wrap .funiter-menu-current-panel-title').remove();}
else{$('.funiter-menu-panels-actions-wrap .funiter-menu-prev-panel').attr('href','#'+new_parent_panel_id).attr('data-cur-panel',target_id).attr('data-target','#'+new_parent_panel_id);var item_title=$('#'+new_parent_panel_id).find('.funiter-menu-next-panel[data-target="'+target_id+'"]').closest('.menu-item').find('.funiter-menu-item-title').attr('data-title');item_title=$(this).data('prenttitle');if(typeof item_title!='undefined'&&typeof item_title!=false){if(!$('.funiter-menu-panels-actions-wrap .funiter-menu-current-panel-title').length){$('.funiter-menu-panels-actions-wrap').prepend('<span class="funiter-menu-current-panel-title"></span>');}
$('.funiter-menu-panels-actions-wrap .funiter-menu-current-panel-title').html(item_title);}
else{$('.funiter-menu-panels-actions-wrap .funiter-menu-current-panel-title').remove();}}
e.preventDefault();});});$(document).on("resize",function(){funiter_resizeMegamenu();funiter_auto_width_vertical_menu();});$(document).ready(function(){funiter_auto_width_vertical_menu();});$(window).load(function(){funiter_menuclone_all_menus();});})(jQuery);